name: CI
on:
  pull_request:
    branches: [ 'dev' ]
permissions:
  contents: read
  pull-requests: read
jobs:
  format-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          
      - name: Check Spotless Format
        run: ./gradlew spotlessCheck
        
      - name: Create test directories
        run: mkdir -p /tmp/test-uploads/profileImage
        
      - name: Build and Test
        run: ./gradlew build
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_CONFIG_LOCATION: "classpath:/application-test.yml"
  
  deploy:
    needs: format-and-build
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        uses: appleboy/ssh-action@v1
        env: 
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: | 
            cd /home/ubuntu/project/reserve-mate-backend
            rm -rf src/main/resoruces/application.properties
            git pull origin dev
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.properties
            ./gradlew build -x test
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &